import React, { useState, useCallback } from 'react';
import { AIVendingAnalysis, MachineProfile, CompanyInfo } from '../../types';
import { ChevronDownIcon } from '../icons/ChevronDownIcon';
import { PrinterIcon } from '../icons/PrinterIcon';

// --- Robust Script Loader ---
const scriptPromises: Record<string, Promise<void>> = {};
const loadScript = (src: string): Promise<void> => {
    if (scriptPromises[src]) {
        return scriptPromises[src];
    }
    scriptPromises[src] = new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = src;
        script.async = true;
        script.onload = () => resolve();
        script.onerror = () => {
            delete scriptPromises[src];
            reject(new Error(`Failed to load script: ${src}.`));
        };
        document.head.appendChild(script);
    });
    return scriptPromises[src];
};


interface AISummaryReportProps {
    analysisResult: AIVendingAnalysis;
    machineProfile: MachineProfile;
    companyInfo: CompanyInfo;
}

const AISummaryReport: React.FC<AISummaryReportProps> = ({ analysisResult, machineProfile, companyInfo }) => {
    const [isOpen, setIsOpen] = useState(false);
    const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
    
    const { fullReport: report } = analysisResult;
    
    const handleGeneratePdf = useCallback(async (e: React.MouseEvent) => {
        e.stopPropagation();
        setIsGeneratingPdf(true);
        try {
            await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.10/pdfmake.min.js');
            await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.10/vfs_fonts.js');

            const pdfMake = (window as any).pdfMake;
            if (!pdfMake || !pdfMake.createPdf) {
                throw new Error("PDF generation library (pdfMake) failed to initialize correctly. Please try refreshing the page.");
            }

            const { headerStats, fullReport } = analysisResult;

            const formatCurrency = (amount: number, digits = 2) => {
                return new Intl.NumberFormat('en-MY', {
                    style: 'currency',
                    currency: 'MYR',
                    minimumFractionDigits: digits,
                    maximumFractionDigits: digits
                }).format(amount).replace('MYR', 'RM ');
            };

            const docDefinition = {
                pageSize: 'A4',
                pageMargins: [40, 80, 40, 60],
                header: {
                    columns: [
                        companyInfo.logo ? {
                            image: companyInfo.logo,
                            width: 70,
                            margin: [40, 20, 0, 0]
                        } : {},
                        {
                            stack: [
                                { text: companyInfo.name, style: 'header' },
                                { text: 'AI Smart Vending Analysis Report', style: 'subheader' }
                            ],
                            alignment: 'right',
                            margin: [0, 25, 40, 0]
                        }
                    ]
                },
                footer: (currentPage: number, pageCount: number) => ({
                    columns: [
                        { text: 'Generated by RBE-AI Business Intelligence', alignment: 'left', style: 'footer' },
                        { text: `Page ${currentPage} of ${pageCount}`, alignment: 'right', style: 'footer' }
                    ],
                    margin: [40, 20, 40, 0]
                }),
                content: [
                    { text: `Analysis for Machine: ${machineProfile.machineId}`, style: 'h1' },
                    { text: `Location: ${machineProfile.location} (${machineProfile.environment})`, style: 'p' },
                    { text: `Generated on: ${new Date().toLocaleDateString('en-GB')} at ${new Date().toLocaleTimeString()}`, style: 'p' },
                    { canvas: [{ type: 'line', x1: 0, y1: 5, x2: 515, y2: 5, lineWidth: 1, lineColor: '#cccccc' }], margin: [0, 10, 0, 20] },

                    { text: 'Executive Summary', style: 'h2' },
                    {
                        columns: [
                            {
                                stack: [
                                    { text: 'Est. Return on Investment (ROI)', style: 'summaryLabel' },
                                    { text: `${headerStats.roiMonths.toFixed(1)} months`, style: 'summaryValue', color: '#059669' },
                                ],
                            },
                            {
                                stack: [
                                    { text: 'Avg. Daily Profit (@60% turnover)', style: 'summaryLabel' },
                                    { text: formatCurrency(headerStats.avgDailyProfit, 2), style: 'summaryValue' },
                                ]
                            },
                            {
                                stack: [
                                    { text: 'Avg. Daily Power Cost', style: 'summaryLabel' },
                                    { text: formatCurrency(headerStats.powerCostPerDay, 2), style: 'summaryValue', color: '#D2042D' },
                                ]
                            }
                        ],
                        margin: [0, 0, 0, 20]
                    },

                    { text: 'AI Analysis & Insights', style: 'h2' },
                    { text: fullReport.summary, style: 'p', margin: [0, 0, 0, 15] },

                    { text: 'AI Forecast', style: 'h2' },
                    { text: fullReport.forecast, style: 'p', margin: [0, 0, 0, 15] },

                    { text: 'Actionable Recommendations', style: 'h2' },
                    {
                        ul: fullReport.recommendations.map(rec => ({ text: rec, margin: [0, 0, 0, 5] })),
                        style: 'p'
                    },
                ],
                styles: {
                    header: { fontSize: 24, bold: true, color: '#000000' },
                    subheader: { fontSize: 10, color: '#333333' },
                    h1: { fontSize: 18, bold: true, margin: [0, 0, 0, 5], color: '#D2042D' },
                    h2: { fontSize: 14, bold: true, margin: [0, 15, 0, 8], color: '#000000', border: [false, false, false, true], borderColor: '#cccccc', padding: [0,0,0,2]},
                    p: { fontSize: 10, color: '#333333', lineHeight: 1.4 },
                    summaryLabel: { fontSize: 9, color: '#555555', bold: true },
                    summaryValue: { fontSize: 16, bold: true, color: '#000000' },
                    footer: { fontSize: 8, italics: true, color: '#aaaaaa' }
                }
            };

            pdfMake.createPdf(docDefinition).download(`SmartVend_Report_${machineProfile.machineId}.pdf`);

        } catch (error: any) {
            console.error("PDF Generation Error:", error);
            alert(`Sorry, there was an error generating the PDF: ${error.message}`);
        } finally {
            setIsGeneratingPdf(false);
        }
    }, [analysisResult, machineProfile, companyInfo]);
    
    return (
        <div className="bg-white p-6 rounded-xl shadow-lg border border-gray-200">
            <div className="flex justify-between items-center cursor-pointer" onClick={() => setIsOpen(!isOpen)}>
                <h3 className="text-xl font-bold text-brand-text">🧾 AI Business Insight Report</h3>
                <div className="flex items-center space-x-4">
                     <button 
                        onClick={handleGeneratePdf} 
                        disabled={isGeneratingPdf}
                        className="flex items-center space-x-2 px-3 py-1.5 bg-brand-red text-white rounded-md hover:bg-red-700 text-sm font-semibold disabled:opacity-60 disabled:cursor-wait"
                    >
                        <PrinterIcon className="w-4 h-4" />
                        <span>{isGeneratingPdf ? 'Generating...' : 'Download Full Report'}</span>
                    </button>
                    <ChevronDownIcon className={`w-6 h-6 text-gray-500 transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`} />
                </div>
            </div>
            
            <div className={`transition-all duration-500 ease-in-out overflow-hidden ${isOpen ? 'max-h-[1000px] opacity-100 mt-4 pt-4 border-t' : 'max-h-0 opacity-0'}`}>
                <div className="prose prose-sm max-w-none">
                    <div className="grid grid-cols-2 gap-4 mb-4 text-xs bg-gray-50 p-3 rounded-md">
                        <p><strong>Machine:</strong> {machineProfile.machineId} ({machineProfile.machineModel})</p>
                        <p><strong>Location:</strong> {machineProfile.location}</p>
                        <p><strong>Type:</strong> {machineProfile.machineType}</p>
                        <p><strong>Power:</strong> {machineProfile.powerConsumptionW}W</p>
                    </div>

                    <h4>Summary</h4>
                    <p>{report.summary}</p>

                    <h4>AI Forecast</h4>
                    <p>{report.forecast}</p>

                    <h4>Recommendations</h4>
                    <ul>
                        {report.recommendations.map((rec, index) => (
                            <li key={index}>{rec}</li>
                        ))}
                    </ul>
                </div>
            </div>
        </div>
    );
};

export default AISummaryReport;